version: 2
jobs:
  buildpy2:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: 
        name: Install wget
        command: apt-get update && apt-get install -y wget
      - run:
        name: pip install dependencies
        command: pip install coverall
      - run:
        name: install mir
        command: pip install -e .
      - run:
        name: Run tests
        command: nosetests --with-coverage --cover-erase --cover-package=mir_datset_loaders -v -w tests/
workflows:
  version: 2
  build_and_test:
    jobs:
      - buildpy2


